force-app/main/default/objects/Experian_Configuration__c/Experian_Configuration__c.object-meta.xml
<CustomObject>
    <label>Experian Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experian Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experian_Configuration__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>DISABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Experian_Logs__c/Experian_Logs__c.object-meta.xml
<CustomObject>
    <label>Experian Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Experian Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experian Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experian_Logs__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experian_Logs__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ExperianLogger.cls
public without sharing class ExperianLogger {
  public enum LogLevel {
    DISABLED,
    ERROR,
    WARN,
    INFO,
    DEBUG
  }

  private static LogLevel currentLogLevel;

  static {
    initializeLogLevel();
  }

  private static void initializeLogLevel() {
    try {
      Experian_Configuration__c settings = [
        SELECT Log_Level__c
        FROM Experian_Configuration__c
        LIMIT 1
      ];
      if (settings != null && String.isNotBlank(settings.Log_Level__c)) {
        currentLogLevel = LogLevel.valueOf(settings.Log_Level__c);
        System.debug('currentLogLevel: ' + currentLogLevel);
      } else {
        currentLogLevel = LogLevel.ERROR; // Default log level
      }
    } catch (Exception e) {
      System.debug('Failed to initialize log level: ' + e.getMessage());
      currentLogLevel = LogLevel.ERROR; // Fallback to ERROR level
    }
  }

  public static void log(String message, LogLevel logLevel) {
    if (shouldLog(logLevel)) {
      // Truncate the message if it's longer than 255 characters
      String truncatedMessage = message.length() > 254
        ? message.substring(0, 248) + '...'
        : message;

      Experian_Logs__c logEntry = new Experian_Logs__c(
        Message__c = truncatedMessage,
        Log_Level__c = logLevel.name()
      );

      try {
        insert logEntry;
      } catch (Exception e) {
        throw e;
        // handleLoggingError(e, truncatedMessage, logLevel);
      }
    }
  }

  private static Boolean shouldLog(LogLevel logLevel) {
    if (currentLogLevel == null) {
      initializeLogLevel();
    }
    return logLevel.ordinal() > ExperianLogger.LogLevel.DISABLED.ordinal() &&
      logLevel.ordinal() <= currentLogLevel.ordinal();
  }

  private static void handleLoggingError(
    Exception e,
    String originalMessage,
    LogLevel originalLogLevel
  ) {
    String errorMessage =
      'Failed to log message. Original message: ' +
      originalMessage +
      '. Original log level: ' +
      originalLogLevel +
      '. Error: ' +
      e.getMessage();
    System.debug(LoggingLevel.ERROR, errorMessage);
    // Consider implementing additional error handling here, such as sending an email alert
  }
}