force-app/main/default/objects/Experian_Configuration__c/Experian_Configuration__c.object-meta.xml
<CustomObject>
    <label>Experian Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experian Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experian_Configuration__c/fields/Experian_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Experian_Access_Token__c</fullName>
    <label>Experian Access Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Experian_Configuration__c/fields/Experian_API_Client_id__c.field-meta.xml
<CustomField>
    <fullName>Experian_API_Client_id__c</fullName>
    <label>Experian API Client id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experian_Configuration__c/fields/Experian_Api_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Experian_Api_Client_Secret__c</fullName>
    <label>Experian Api Client Secret</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Experian_Configuration__c/fields/Experian_API_Password__c.field-meta.xml
<CustomField>
    <fullName>Experian_API_Password__c</fullName>
    <label>Experian API Password</label>
    <length>100</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Experian_Configuration__c/fields/Experian_API_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Experian_API_User_Name__c</fullName>
    <label>Experian API User Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experian_Configuration__c/fields/Experian_Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Experian_Token_URL__c</fullName>
    <label>Experian Token URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ExperianApiService.cls
public inherited sharing class ExperianApiService {
  public static Experian_Configuration__c getBIQConfig() {
    return [
      SELECT
        Id,
        Name,
        Experian_Access_Token__c,
        Experian_API_Client_id__c,
        Experian_Api_Client_Secret__c,
        Experian_API_Password__c,
        Experian_API_User_Name__c,
        Experian_Token_URL__c
      FROM Experian_Configuration__c
      LIMIT 1
    ];
  }
}